$('#conas-ed').click(function(){
    $('#resetp').show();
});
$('#conas-st').click(function(){
    $('#resetpst').show();
});
$('#conas-otest').click(function(){
    $('#rst-ont').show();
});
$('#conas-exmp').click(function(){
    $('#rst-emp').show();
});